version: '3'
services:
  datasource:
    build: 
      context: ./datasource
    depends_on:
      - mongo
    volumes:
      - ./datasource:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '80:3000'
    container_name: datasource
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
      SEED: "${SEED}"

  nextjs:
    build:
      context: ./nextapp
    ports:
      - "3000:3000"
    container_name: nextjs
    stdin_open: true
    environment:
      DATASOURCE_URL: "http://datasource:3000/"
    volumes:
       - ./nextapp:/usr/src/app
       - /usr/src/app/node_modules

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    logging:
      driver: "none"

volumes:
  mongodb:
