version: '3'
services:
  app:
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    ports:
      - '80:3000'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  mongodb:
